staticman:
  port: '80'
  githubToken: 'c690fb37070fc67bf7f1b9d36fe7ecc9d6b087fc'
  branch: 'master'
  allowedFields: ['name', 'markdown', 'message']
  requiredFields: ['name', 'message']
  format: 'json'
  moderation: false
  path: _data/{options.slug}
  filename: comment-{@timestamp}
  generatedFields:
    date:
      type: "date"
      options:
        format: "iso8601"
